column_width = 100
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Input"
collapse_simple_statement = "ConditionalOnly"
syntax = "LuaJIT"

[sort_requires]
enabled = true
